services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      # - prometheus-data:/prometheus
    networks:
      - observability
  
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    ports:
      - 3000:3000
    networks:
      - observability
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus

  # App

  spring:
    build: ./app
    container_name: spring-observability
    ports:
      - 8080:8080
    networks:
      - observability
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./cert/cert.crt:/etc/nginx/ssl/cert.crt
      - ./cert/cert.key:/etc/nginx/ssl/cert.key
    networks:
      - observability
    restart: unless-stopped

networks:
  observability:
    driver: bridge
    name: observability

volumes:
  prometheus-data:
    name: prometheus-data
  grafana-data:
    name: grafana-data